### PR TITLE
Load config from spicedb.env

### PR DESCRIPTION
**Pull request by suttod**
closes https://github.com/authzed/spicedb/issues/1082
Depends on https://github.com/jzelinskie/cobrautil/pull/48
Doc: https://github.com/authzed/docs/pull/127

### CODE REVIEW

**Comment by josephschorr** [comment]
@suttod Can you please rebase?

**Comment by suttod** [comment]
@josephschorr rebased. Please note that it won't compile until https://github.com/jzelinskie/cobrautil/pull/48 is merged.

**Comment by jzelinskie** [comment]
https://github.com/jzelinskie/cobrautil/pull/48 is merged.

**Comment by josephschorr** [comment]
@suttod please rebase

**Comment by suttod** [comment]
@jzelinskie added some error handling to cobrautil before merging the changes, so that existence of env file is required now. This breaks backward compatibility of spicedb cli (raises: `Error: open spicedb.env: no such file or directory` with default config). My expectation was to silently ignore loading env file, if it doesn't exist (or at most log an info-level message).

Now I'm somewhat confused, which would be the best from user/developer experience:

1. The cleanest option would be to add a command line flag / envvar option to load further variables from (eg. `--spicedb-envfile=./spicedb.env`). Though it would introduce the need of some preprocessing of env/flags, and might be more difficult to maintain.
2. Implement some fallback in pkg/cmd/server/default.go to pass error with loading envfile. Would require double execution of `cobrautil.CobraRunFunc` (when the first fails). Can introduce further regression as `fs.PathError` migh be raised from other source as well. 
3. Instead of using `SyncViperDotEnvPreRunE` of cobrautil, load envfile in sipcedb (`pkg/cmd/server/default.go:DefaultPreRunE`), and handle error if file doesn't exist (log/pass)
4. Keep cobrautil siletnly pass if file doesn't exist.

Which do you prefer?

**Comment by jzelinskie** [comment]
Hey there! Sorry for the delayed response.

I added the additional error handling with the intent of enabling a caller to choose the behavior they want in the case when the file is missing. Some observations looking back on it now:

1. It's awkward because you have to wrap the function to catch the error
2. I probably need to wrap the error and define yet another error type so that it can be more easily detected
3. 1+2 is a bunch of boilerplate for what is ultimately the default behavior

I think ultimately most programs using dotenv expect the default to load or fallback. If you agree with 1-3, I'll change it back to your original behavior and add logging when it loads successfully.

**Comment by suttod** [comment]
Hi, I ultimately agree with your observations, especially with the "load-or-fallback" behavior.

So lets go with my 4th suggestion:
> Keep cobrautil siletnly pass if file doesn't exist.

Will you change in cobrautil, or shall I raise a separate MR?

**Comment by suttod** [comment]
> Hi, I ultimately agree with your observations, especially with the "load-or-fallback" behavior.
> 
> So lets go with my 4th suggestion:
> 
> > Keep cobrautil siletnly pass if file doesn't exist.
> 
> Will you change in cobrautil, or shall I raise a separate MR?

Raised a new [MR](https://github.com/jzelinskie/cobrautil/pull/49) in cobrautil that only prints a notification when spicedb.env not found. Also rebased to main branch.

**Comment by jzelinskie** [comment]
I added a commit so that the info line produced in cobrautil can use the zerolog logger in SpiceDB. Can we pull that in as well?

**Comment by suttod** [comment]
> I added a commit so that the info line produced in cobrautil can use the zerolog logger in SpiceDB. Can we pull that in as well?

Seems reasonable, but please note that when parsing the dotenv file, we are still before processing any configuration. Zerolog as well.

**Review by jzelinskie — APPROVED** [review]

**Pull request merged**
