### PR TITLE
Support credential JSON for Spanner

### LINKED ISSUE #1941: Allow credential JSON for Spanner options
### Problem Statement

I am using SpiceDB library mode with Spanner for testing.
And I want to pass `CredentialsJSON` for Spanner.

### Solution Brainstorm

Add `credentialsJSON` for `spannerOptions`

I will send a PR.

### PR DESCRIPTION
**Pull request by lexcao**
Closes #1941

### CODE REVIEW

**Comment by lexcao** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by lexcao** [comment]
recheck

**Comment by josephschorr** [comment]
@lexcao I'm curious: how is this different from `credentialsFile`?

**Comment by lexcao** [comment]
Hi @josephschorr 
The `credentialsFile` would read the credential JSON from file system.
The `credentialsJSON` is the JSON content for no matter where it comes from.

In my use case, I use SpiceDB library and my Spanner credential is fetched from remote server like config center.

**Review by josephschorr — APPROVED** [review]
LGTM

**Pull request merged**
