### PR TITLE
Add mention about PHP library to README

### PR DESCRIPTION
**Pull request by amsprost**
There's a PHP client library based on REST protocol (because of issues with generation from proto 2 & PHP). Since client libraries are official repos under authzed organisation, but because it can be beneficial for PHP developers to use this library in order being able to manage app permissions maybe can be useful to have a link related to this library in README. If you have better idea how to mention PHP library in this repo - please let me know, I'm open to suggestions

### CODE REVIEW

**Comment by amsprost** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by vroldanbet — CHANGES_REQUESTED** [review]
Hey @amsprost, thanks for the contribution! We are deliberately not exhaustive with client libraries in the spicedb repository. Instead we list those under the https://github.com/authzed/awesome-spicedb repo. We have there a PHP library listed already, we weren't aware of this one. What are the differences?

**Comment by amsprost** [comment]
> Hey @amsprost, thanks for the contribution! We are deliberately not exhaustive with client libraries in the spicedb repository. Instead we list those under the https://github.com/authzed/awesome-spicedb repo. We have there a PHP library listed already, we weren't aware of this one. What are the differences?

Thanks @vroldanbet ! I wasn't aware of that other PHP library and that other repo. Perhaps, it can be mentioned more explicitly inside README.md on the main repo of SpiceDB as atm it shows only official libraries, so hard to get awareness of non-official libraries.

But as for other PHP library it's mentioned there that it's not production ready & there's no plans to fix that. Also that lib requires PHP 8.0, as mine can work on PHP 7.4. All other differences are minor as that lib is also based on REST API.

But thank you very much for feedback, I'm closing this PR & will open a new one to https://github.com/authzed/awesome-spicedb

**Comment by vroldanbet** [comment]
@amsprost thank you for the feedback! I've opened https://github.com/authzed/spicedb/pull/1076 to link to awesome-spicedb repo instead, which should keep a more exhaustive list of client libraries. 

As for the PHP library, I think if we conclude https://github.com/linkorb/spicedb-php is better suited for PHP users, we would be happy to list it in awesome-spicedb. @jzelinskie could you perhaps have a look at https://github.com/linkorb/spicedb-php and see if it makes the cut to awesome-spicedb as replacement of the currently listed one?

**Pull request closed without merging**
