### PR TITLE
refactor(schemadsl): remove unused field

### PR DESCRIPTION
**Pull request by fearlessfe**
remove unused field 'lastNonWhitespaceToken' in Lexer

issue#619

I have read the CLA Document and I hereby sign the CLA

recheck

### CODE REVIEW

**Comment by fearlessfe** [comment]
recheck

**Comment by josephschorr** [comment]
@fearlessfe Add a new comment with the approval text

**Comment by fearlessfe** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by fearlessfe** [comment]
@josephschorr it worked.

**Review by josephschorr — APPROVED** [review]
LGTM

**Pull request merged**
