### PR TITLE
fixed lsp panicing on formatting malformed content

### PR DESCRIPTION
**Pull request by sabify**

### CODE REVIEW

**Comment by sabify** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sabify** [comment]
recheck

**Review by vroldanbet — APPROVED** [review]
nice catch!

**Comment by josephschorr** [comment]
@sabify Mind adding a test?

**Comment by sabify** [comment]
@josephschorr Added.

**Comment by josephschorr** [comment]
@sabify Please rebase

**Comment by sabify** [comment]
@josephschorr Done.

**Comment by sabify** [comment]
Is the failed workflow related to this PR?

**Comment by josephschorr** [comment]
Likely a flake

**Review by josephschorr — APPROVED** [review]
LGTM

**Pull request merged**
