### PR TITLE
Add ClusterfuzzLite

### PR DESCRIPTION
**Pull request by AdamKorcz**
This PR adds [ClusterfuzzLite](https://google.github.io/clusterfuzzlite/) to the CI. 

CFLite will run the fuzzer in this PR - as well as other fuzzers that get added - in the CI when a new PR is made.

### CODE REVIEW

**Comment by AdamKorcz** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jzelinskie** [comment]
Hello there!

Fuzzing is definitely something we'd like to add to our test suites.

Google's ClusterfuzzLite looks pretty useful -- I like how containerd is leveraging it [in their workflows](https://github.com/containerd/containerd/blob/db3ecb286bd5f082d13ae9d5646f189a7d284805/.github/workflows/fuzz.yml#L6-L31) as it doesn't introduce any new files into their repository.

What is the advantage to using the AdaLogistics library over the built-in functionality in Go 1.18?

**Comment by AdamKorcz** [comment]
> What is the advantage to using the AdaLogistics library over the built-in functionality in Go 1.18?

The go-fuzz-headers library offers a number of useful features for fuzzing, but these do not conflict with the Go 1.18 fuzzing engine. If you would prefer to have a Go 1.18 fuzzer, I can rewrite it.

**Comment by jzelinskie** [comment]
I think using the Go 1.18 fuzzing is best until we can justify adding the dependency.

I also took a look at [Prometheus's usage of ClusterFuzz](https://github.com/prometheus/prometheus/blob/main/.github/workflows/fuzzing.yml) and it looks really good.

**Comment by jzelinskie** [comment]
@AdamKorcz any updates here?

**Comment by AdamKorcz** [comment]
> @AdamKorcz any updates here?

Sorry for the delay. I will look into changing the fuzzers to the 1.18 engine when I get a moment. Thanks for the ping!

**Comment by vroldanbet** [comment]
hey @AdamKorcz, thanks again for your contribution! we thought it would be good to get this over the finish line so I started investigating how it works in https://github.com/authzed/spicedb/pull/830.

We thought it would be a good idea to submit our project to `oss-fuzz`. The latter supports go native fuzzing via a script [you wrote](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/compile_native_go_fuzzer) 😄  I have the project submission almost ready.

ClusterFuzzLite docs indicate it is based on OSS-fuzz framework, but only supports  `libFuzzer`. Is this outdated documentation? can we also do `compile_native_go_fuzzer` in ClusterFuzzLite?

**Comment by AdamKorcz** [comment]
OSS-Fuzz integration would be great.

> can we also do `compile_native_go_fuzzer` in ClusterFuzzLite?

I assume you mean in OSS-Fuzz? The answer is yes.

**Comment by vroldanbet** [comment]
@AdamKorcz I actually meant OssFuzzLite. The reason I ask is that I have doubts oss-fuzz will accept our submission in a promptly manner. There are 210 open PRs in the repository, so running ClusterFuzzLite ourselves in our CI pipeline would allow us to iterate faster. Thoughts?

**Comment by vroldanbet** [comment]
> OssFuzzLite

whoops meant ClusterFuzzLite

>The OSS-Fuzz project should review the submission fairly fast. Your PR will not be 211 in line. However, do note that OSS-Fuzz will only accept the integration in case SpiceDB can disclosure a critical user base (companies, other open source projects etc)

Understood! I think we can get started with ClusterFuzzLite using native go fuzzing, and once we have the submission ready we can move to oss-fuzz if we get accepted

Thanks a ton!

**Comment by AdamKorcz** [comment]
> `compile_native_go_fuzzer`

whoops meant ClusterFuzzLite, ah I see. Yes, `compile_native_go_fuzzer` works in CFL too. It depends heavily on https://github.com/AdamKorcz/go-118-fuzz-build, so if you experience any issues, feel free to open a ticket there.

**Comment by vroldanbet** [comment]
@AdamKorcz My PR https://github.com/authzed/spicedb/pull/830 seems to be finally running CFL (added you as co-author 😄 ), although it's running out of memory. Any advice on how to tune it to work with the resources available in Actions runners?

Feel free to close this one!

**Comment by josephschorr** [comment]
@AdamKorcz ping on this

**Comment by josephschorr** [comment]
Closing; feel free to reopen if necessary

**Pull request closed without merging**
