### PR TITLE
returns proper error reason for duplicate relationships

### PR DESCRIPTION
**Pull request by vroldanbet**
Closes https://github.com/authzed/spicedb/issues/1366

### CODE REVIEW

**Comment by reify-tanner-stirrat** [comment]
Ah damn you beat me to it :(

**Comment by vroldanbet** [comment]
@reify-tanner-stirrat I'm more than happy to close this one and let you open the PR, you reported it in the first place after all!

**Comment by reify-tanner-stirrat** [comment]
sounds good - thank you!

**Comment by reify-tanner-stirrat** [comment]
See #1367

**Comment by vroldanbet** [comment]
Closing in favour of https://github.com/authzed/spicedb/pull/1367

**Pull request closed without merging**
