### PR TITLE
Inform Docker of the port that spicedb listens on

### PR DESCRIPTION
**Pull request by drew-richardson**

### CODE REVIEW

**Comment by drew-richardson** [comment]
I have read the CLA Document and I hereby sign the CLA

recheck

**Comment by drew-richardson** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by drew-richardson** [comment]
recheck

**Comment by drew-richardson** [comment]
retry

**Review by josephschorr — APPROVED** [review]
LGTM

**Pull request merged**
