### PR TITLE
pkg/datastore: fix typo in godoc

### PR DESCRIPTION
**Pull request by gkelly**

### CODE REVIEW

**Review by ecordell — APPROVED** [review]
LGTM, but please sign the CLA so we can merge

Thanks for improving the docs!

**Comment by josephschorr** [comment]
@gkelly Please sign the CLA so we can merge

**Comment by josephschorr** [comment]
@gkelly Please sign the CLA

**Comment by josephschorr** [comment]
Closing in favor of https://github.com/authzed/spicedb/pull/1726

**Pull request closed without merging**
